import { createContext, useContext, useMemo, useState, type ReactNode } from 'react';

export type LanguageOption =
  | 'English'
  | 'Spanish'
  | 'French'
  | 'German'
  | 'Italian'
  | 'Portuguese'
  | 'Dutch'
  | 'Arabic'
  | 'Hindi'
  | 'Japanese'
  | 'Korean'
  | 'Chinese (Simplified)'
  | 'Chinese (Traditional)'
  | 'Russian'
  | 'Turkish'
  | 'Polish'
  | 'Swedish'
  | 'Norwegian'
  | 'Danish'
  | 'Finnish';

const LANGUAGE_KEY = 'devops-ai-monitor-language';

const translations: Record<string, Record<string, string>> = {
  'app.title': { English: 'DevOps Shield', Spanish: 'DevOps Shield', French: 'DevOps Shield', German: 'DevOps Shield', Italian: 'DevOps Shield', Portuguese: 'DevOps Shield', Dutch: 'DevOps Shield', Arabic: 'DevOps Shield', Hindi: 'DevOps Shield', Japanese: 'DevOps Shield', Korean: 'DevOps Shield', 'Chinese (Simplified)': 'DevOps Shield', 'Chinese (Traditional)': 'DevOps Shield', Russian: 'DevOps Shield', Turkish: 'DevOps Shield', Polish: 'DevOps Shield', Swedish: 'DevOps Shield', Norwegian: 'DevOps Shield', Danish: 'DevOps Shield', Finnish: 'DevOps Shield' },
  'nav.dashboard': { English: 'Dashboard', Spanish: 'Panel', French: 'Tableau de bord', German: 'Dashboard', Italian: 'Dashboard', Portuguese: 'Painel', Dutch: 'Dashboard', Arabic: 'لوحة التحكم', Hindi: 'डैशबोर्ड', Japanese: 'ダッシュボード', Korean: '대시보드', 'Chinese (Simplified)': '仪表板', 'Chinese (Traditional)': '儀表板', Russian: 'Панель', Turkish: 'Kontrol Paneli', Polish: 'Pulpit', Swedish: 'Instrumentpanel', Norwegian: 'Kontrollpanel', Danish: 'Dashboard', Finnish: 'Kojelauta' },
  'nav.repositories': { English: 'Repositories', Spanish: 'Repositorios', French: 'Dépôts', German: 'Repositories', Italian: 'Repository', Portuguese: 'Repositórios', Dutch: 'Repositories', Arabic: 'المستودعات', Hindi: 'रिपोजिटरी', Japanese: 'リポジトリ', Korean: '저장소', 'Chinese (Simplified)': '仓库', 'Chinese (Traditional)': '倉庫', Russian: 'Репозитории', Turkish: 'Depolar', Polish: 'Repozytoria', Swedish: 'Repo', Norwegian: 'Repoer', Danish: 'Repositorier', Finnish: 'Varastot' },
  'nav.pipelines': { English: 'Azure DevOps Pipelines', Spanish: 'Pipelines de Azure DevOps', French: 'Pipelines Azure DevOps', German: 'Azure DevOps-Pipelines', Italian: 'Pipeline Azure DevOps', Portuguese: 'Pipelines do Azure DevOps', Dutch: 'Azure DevOps-pijplijnen', Arabic: 'خطوط أنابيب Azure DevOps', Hindi: 'Azure DevOps पाइपलाइंस', Japanese: 'Azure DevOps パイプライン', Korean: 'Azure DevOps 파이프라인', 'Chinese (Simplified)': 'Azure DevOps 管道', 'Chinese (Traditional)': 'Azure DevOps 管道', Russian: 'Конвейеры Azure DevOps', Turkish: 'Azure DevOps Boru Hatları', Polish: 'Potoki Azure DevOps', Swedish: 'Azure DevOps-pipelines', Norwegian: 'Azure DevOps-pipelines', Danish: 'Azure DevOps-pipelines', Finnish: 'Azure DevOps-putket' },
  'nav.codeQuality': { English: 'Code Quality', Spanish: 'Calidad del código', French: 'Qualité du code', German: 'Code-Qualität', Italian: 'Qualità del codice', Portuguese: 'Qualidade do código', Dutch: 'Codekwaliteit', Arabic: 'جودة الكود', Hindi: 'कोड गुणवत्ता', Japanese: 'コード品質', Korean: '코드 품질', 'Chinese (Simplified)': '代码质量', 'Chinese (Traditional)': '代碼品質', Russian: 'Качество кода', Turkish: 'Kod Kalitesi', Polish: 'Jakość kodu', Swedish: 'Kodkvalitet', Norwegian: 'Kodekvalitet', Danish: 'Kodekvalitet', Finnish: 'Koodin laatu' },
  'nav.settings': { English: 'Settings', Spanish: 'Configuración', French: 'Paramètres', German: 'Einstellungen', Italian: 'Impostazioni', Portuguese: 'Configurações', Dutch: 'Instellingen', Arabic: 'الإعدادات', Hindi: 'सेटिंग्स', Japanese: '設定', Korean: '설정', 'Chinese (Simplified)': '设置', 'Chinese (Traditional)': '設定', Russian: 'Настройки', Turkish: 'Ayarlar', Polish: 'Ustawienia', Swedish: 'Inställningar', Norwegian: 'Innstillinger', Danish: 'Indstillinger', Finnish: 'Asetukset' },
  'auth.signIn': { English: 'Sign in', Spanish: 'Iniciar sesión', French: 'Se connecter', German: 'Anmelden', Italian: 'Accedi', Portuguese: 'Entrar', Dutch: 'Inloggen', Arabic: 'تسجيل الدخول', Hindi: 'साइन इन', Japanese: 'サインイン', Korean: '로그인', 'Chinese (Simplified)': '登录', 'Chinese (Traditional)': '登入', Russian: 'Войти', Turkish: 'Giriş Yap', Polish: 'Zaloguj się', Swedish: 'Logga in', Norwegian: 'Logg inn', Danish: 'Log ind', Finnish: 'Kirjaudu sisään' },
  'auth.signInTitle': { English: 'Sign in to your workspace', Spanish: 'Inicie sesión en su espacio de trabajo', French: 'Connectez-vous à votre espace de travail', German: 'Melden Sie sich in Ihrem Arbeitsbereich an', Italian: 'Accedi al tuo spazio di lavoro', Portuguese: 'Entre no seu espaço de trabalho', Dutch: 'Log in op uw werkruimte', Arabic: 'تسجيل الدخول إلى مساحة العمل الخاصة بك', Hindi: 'अपने वर्कस्पेस में साइन इन करें', Japanese: 'ワークスペースにサインイン', Korean: '작업 공간에 로그인', 'Chinese (Simplified)': '登录到您的工作区', 'Chinese (Traditional)': '登入您的工作區', Russian: 'Войдите в рабочее пространство', Turkish: 'Çalışma alanınıza giriş yapın', Polish: 'Zaloguj się do swojego obszaru roboczego', Swedish: 'Logga in på ditt arbetsutrymme', Norwegian: 'Logg inn på arbeidsområdet ditt', Danish: 'Log ind på dit arbejdsområde', Finnish: 'Kirjaudu työtilaan' },
  'auth.username': { English: 'Username', Spanish: 'Nombre de usuario', French: "Nom d'utilisateur", German: 'Benutzername', Italian: 'Nome utente', Portuguese: 'Nome de usuário', Dutch: 'Gebruikersnaam', Arabic: 'اسم المستخدم', Hindi: 'उपयोगकर्ता नाम', Japanese: 'ユーザー名', Korean: '사용자 이름', 'Chinese (Simplified)': '用户名', 'Chinese (Traditional)': '使用者名稱', Russian: 'Имя пользователя', Turkish: 'Kullanıcı adı', Polish: 'Nazwa użytkownika', Swedish: 'Användarnamn', Norwegian: 'Brukernavn', Danish: 'Brugernavn', Finnish: 'Käyttäjätunnus' },
  'auth.password': { English: 'Password', Spanish: 'Contraseña', French: 'Mot de passe', German: 'Passwort', Italian: 'Password', Portuguese: 'Senha', Dutch: 'Wachtwoord', Arabic: 'كلمة المرور', Hindi: 'पासवर्ड', Japanese: 'パスワード', Korean: '비밀번호', 'Chinese (Simplified)': '密码', 'Chinese (Traditional)': '密碼', Russian: 'Пароль', Turkish: 'Şifre', Polish: 'Hasło', Swedish: 'Lösenord', Norwegian: 'Passord', Danish: 'Adgangskode', Finnish: 'Salasana' },
  'auth.rememberMe': { English: 'Remember me', Spanish: 'Recuérdame', French: 'Se souvenir de moi', German: 'Angemeldet bleiben', Italian: 'Ricordami', Portuguese: 'Lembrar de mim', Dutch: 'Onthoud mij', Arabic: 'تذكرني', Hindi: 'मुझे याद रखें', Japanese: 'パスワードを保存', Korean: '로그인 상태 유지', 'Chinese (Simplified)': '记住我', 'Chinese (Traditional)': '記住我', Russian: 'Запомнить меня', Turkish: 'Beni hatırla', Polish: 'Zapamiętaj mnie', Swedish: 'Kom ihåg mig', Norwegian: 'Husk meg', Danish: 'Husk mig', Finnish: 'Muista minut' },
  'auth.forgotPassword': { English: 'Forgot password?', Spanish: '¿Olvidó su contraseña?', French: 'Mot de passe oublié ?', German: 'Passwort vergessen?', Italian: 'Password dimenticata?', Portuguese: 'Esqueceu a senha?', Dutch: 'Wachtwoord vergeten?', Arabic: 'هل نسيت كلمة المرور؟', Hindi: 'पासवर्ड भूल गए?', Japanese: 'パスワードをお忘れですか？', Korean: '비밀번호를 잊으셨나요?', 'Chinese (Simplified)': '忘记密码？', 'Chinese (Traditional)': '忘記密碼？', Russian: 'Забыли пароль?', Turkish: 'Şifrenizi mi unuttunuz?', Polish: 'Zapomniałeś hasła?', Swedish: 'Glömt lösenord?', Norwegian: 'Glemt passord?', Danish: 'Glemt adgangskode?', Finnish: 'Unohditko salasanan?' },
  'auth.register': { English: 'Register', Spanish: 'Registrarse', French: "S'inscrire", German: 'Registrieren', Italian: 'Registrati', Portuguese: 'Registrar', Dutch: 'Registreren', Arabic: 'إنشاء حساب', Hindi: 'रजिस्टर', Japanese: '登録', Korean: '등록', 'Chinese (Simplified)': '注册', 'Chinese (Traditional)': '註冊', Russian: 'Регистрация', Turkish: 'Kayıt Ol', Polish: 'Zarejestruj się', Swedish: 'Registrera', Norwegian: 'Registrer', Danish: 'Tilmeld', Finnish: 'Rekisteröidy' },
  'auth.loginButton': { English: 'Login', Spanish: 'Iniciar sesión', French: 'Connexion', German: 'Anmelden', Italian: 'Accedi', Portuguese: 'Entrar', Dutch: 'Inloggen', Arabic: 'تسجيل الدخول', Hindi: 'लॉगिन', Japanese: 'ログイン', Korean: '로그인', 'Chinese (Simplified)': '登录', 'Chinese (Traditional)': '登入', Russian: 'Войти', Turkish: 'Giriş', Polish: 'Zaloguj', Swedish: 'Logga in', Norwegian: 'Logg inn', Danish: 'Log ind', Finnish: 'Kirjaudu sisään' },
  'auth.createAccount': { English: 'Create your account', Spanish: 'Cree su cuenta', French: 'Créez votre compte', German: 'Erstellen Sie Ihr Konto', Italian: 'Crea il tuo account', Portuguese: 'Crie sua conta', Dutch: 'Maak uw account aan', Arabic: 'إنشاء حسابك', Hindi: 'अपना खाता बनाएं', Japanese: 'アカウントを作成', Korean: '계정 만들기', 'Chinese (Simplified)': '创建您的账户', 'Chinese (Traditional)': '建立您的帳戶', Russian: 'Создайте аккаунт', Turkish: 'Hesabınızı oluşturun', Polish: 'Utwórz konto', Swedish: 'Skapa ditt konto', Norwegian: 'Opprett kontoen din', Danish: 'Opret din konto', Finnish: 'Luo tili' },
  'auth.resetPassword': { English: 'Reset your password', Spanish: 'Restablezca su contraseña', French: 'Réinitialisez votre mot de passe', German: 'Setzen Sie Ihr Passwort zurück', Italian: 'Reimposta la tua password', Portuguese: 'Redefina sua senha', Dutch: 'Reset uw wachtwoord', Arabic: 'إعادة تعيين كلمة المرور', Hindi: 'अपना पासवर्ड रीसेट करें', Japanese: 'パスワードをリセット', Korean: '비밀번호 재설정', 'Chinese (Simplified)': '重置您的密码', 'Chinese (Traditional)': '重設您的密碼', Russian: 'Сбросить пароль', Turkish: 'Şifrenizi sıfırlayın', Polish: 'Zresetuj hasło', Swedish: 'Återställ ditt lösenord', Norwegian: 'Tilbakestill passordet ditt', Danish: 'Nulstil din adgangskode', Finnish: 'Nollaa salasanasi' },
  'auth.forgotPasswordTitle': { English: 'Forgot Password', Spanish: 'Olvidé mi contraseña', French: 'Mot de passe oublié', German: 'Passwort vergessen', Italian: 'Password dimenticata', Portuguese: 'Esqueci minha senha', Dutch: 'Wachtwoord vergeten', Arabic: 'نسيت كلمة المرور', Hindi: 'पासवर्ड भूल गए', Japanese: 'パスワードを忘れた', Korean: '비밀번호 찾기', 'Chinese (Simplified)': '忘记密码', 'Chinese (Traditional)': '忘記密碼', Russian: 'Забыли пароль', Turkish: 'Şifremi unuttum', Polish: 'Zapomniałem hasła', Swedish: 'Glömt lösenord', Norwegian: 'Glemt passord', Danish: 'Glemt adgangskode', Finnish: 'Unohdin salasanan' },
  'dashboard.title': { English: 'Executive Dashboard', Spanish: 'Panel ejecutivo', French: 'Tableau de bord exécutif', German: 'Executive-Dashboard', Italian: 'Dashboard esecutivo', Portuguese: 'Painel executivo', Dutch: 'Executive dashboard', Arabic: 'لوحة القيادة', Hindi: 'कार्यकारी डैशबोर्ड', Japanese: 'エグゼクティブダッシュボード', Korean: '실행 대시보드', 'Chinese (Simplified)': '执行仪表板', 'Chinese (Traditional)': '執行儀表板', Russian: 'Исполнительная панель', Turkish: 'Yönetici Kontrol Paneli', Polish: 'Panel wykonawczy', Swedish: 'Ledningspanel', Norwegian: 'Ledelsesdashbord', Danish: 'Ledelsesdashboard', Finnish: 'Johtoryhmädashboard' },
  'dashboard.repositories': { English: 'Repositories', Spanish: 'Repositorios', French: 'Dépôts', German: 'Repositories', Italian: 'Repository', Portuguese: 'Repositórios', Dutch: 'Repositories', Arabic: 'المستودعات', Hindi: 'रिपोजिटरी', Japanese: 'リポジトリ', Korean: '저장소', 'Chinese (Simplified)': '仓库', 'Chinese (Traditional)': '倉庫', Russian: 'Репозитории', Turkish: 'Depolar', Polish: 'Repozytoria', Swedish: 'Repositorier', Norwegian: 'Repoer', Danish: 'Repositorier', Finnish: 'Varastot' },
  'dashboard.runningPipelines': { English: 'Running Pipelines', Spanish: 'Pipelines en ejecución', French: 'Pipelines en cours', German: 'Laufende Pipelines', Italian: 'Pipeline in esecuzione', Portuguese: 'Pipelines em execução', Dutch: 'Lopende pijplijnen', Arabic: 'الخطوط الجارية', Hindi: 'चल रही पाइपलाइंस', Japanese: '実行中のパイプライン', Korean: '실행 중인 파이프라인', 'Chinese (Simplified)': '运行中的管道', 'Chinese (Traditional)': '執行中的管道', Russian: 'Выполняющиеся конвейеры', Turkish: 'Çalışan Boru Hatları', Polish: 'Uruchomione potoki', Swedish: 'Körande pipelines', Norwegian: 'Kjørende pipelines', Danish: 'Kørende pipelines', Finnish: 'Käynnissä olevat putket' },
  'dashboard.failedPipelines': { English: 'Failed Pipelines', Spanish: 'Pipelines fallidos', French: 'Pipelines en échec', German: 'Fehlgeschlagene Pipelines', Italian: 'Pipeline fallite', Portuguese: 'Pipelines com falha', Dutch: 'Mislukte pijplijnen', Arabic: 'الخطوط الفاشلة', Hindi: 'विफल पाइपलाइंस', Japanese: '失敗したパイプライン', Korean: '실패한 파이프라인', 'Chinese (Simplified)': '失败的管道', 'Chinese (Traditional)': '失敗的管道', Russian: 'Неудачные конвейеры', Turkish: 'Başarısız Boru Hatları', Polish: 'Nieudane potoki', Swedish: 'Misslyckade pipelines', Norwegian: 'Mislykkede pipelines', Danish: 'Mislykkede pipelines', Finnish: 'Epäonnistuneet putket' },
  'dashboard.securityScore': { English: 'Security Score', Spanish: 'Puntuación de seguridad', French: 'Score de sécurité', German: 'Sicherheitsbewertung', Italian: 'Punteggio sicurezza', Portuguese: 'Pontuação de segurança', Dutch: 'Beveiligingsscore', Arabic: 'درجة الأمان', Hindi: 'सुरक्षा स्कोर', Japanese: 'セキュリティスコア', Korean: '보안 점수', 'Chinese (Simplified)': '安全得分', 'Chinese (Traditional)': '安全得分', Russian: 'Оценка безопасности', Turkish: 'Güvenlik Puanı', Polish: 'Ocena bezpieczeństwa', Swedish: 'Säkerhetsresultat', Norwegian: 'Sikkerhetspoeng', Danish: 'Sikkerhedsscore', Finnish: 'Turvallisuuspisteet' },
  'repo.title': { English: 'Repositories', Spanish: 'Repositorios', French: 'Dépôts', German: 'Repositories', Italian: 'Repository', Portuguese: 'Repositórios', Dutch: 'Repositories', Arabic: 'المستودعات', Hindi: 'रिपोजिटरी', Japanese: 'リポジトリ', Korean: '저장소', 'Chinese (Simplified)': '仓库', 'Chinese (Traditional)': '倉庫', Russian: 'Репозитории', Turkish: 'Depolar', Polish: 'Repozytoria', Swedish: 'Repositorier', Norwegian: 'Repoer', Danish: 'Repositorier', Finnish: 'Varastot' },
  'repo.subtitle': { English: 'Browse repositories and their branches in your Azure DevOps or GitHub workspace.', Spanish: 'Explore los repositorios y sus ramas en su espacio de trabajo de Azure DevOps o GitHub.', French: 'Parcourez les dépôts et leurs branches dans votre espace de travail Azure DevOps ou GitHub.', German: 'Durchsuchen Sie Repositories und deren Branches in Ihrem Azure DevOps- oder GitHub-Arbeitsbereich.', Italian: 'Sfoglia repository e i loro branch nel tuo workspace Azure DevOps o GitHub.', Portuguese: 'Navegue pelos repositórios e seus branches no seu workspace do Azure DevOps ou GitHub.', Dutch: 'Blader door repositories en hun branches in uw Azure DevOps- of GitHub-workspace.', Arabic: 'استعرض المستودعات وفروعها في مساحة العمل الخاصة بك على Azure DevOps أو GitHub.', Hindi: 'अपने Azure DevOps या GitHub वर्कस्पेस में रिपोजिटरी और उनके शाखाओं को ब्राउज़ करें।', Japanese: 'Azure DevOps または GitHub ワークスペース内のリポジトリとブランチを参照します。', Korean: 'Azure DevOps 또는 GitHub 작업 공간에서 저장소와 해당 브랜치를 탐색하세요.', 'Chinese (Simplified)': '浏览 Azure DevOps 或 GitHub 工作区中的仓库及其分支。', 'Chinese (Traditional)': '瀏覽 Azure DevOps 或 GitHub 工作區中的倉庫及其分支。', Russian: 'Просматривайте репозитории и их ветки в вашем рабочем пространстве Azure DevOps или GitHub.', Turkish: 'Azure DevOps veya GitHub çalışma alanınızdaki depoları ve dallarını inceleyin.', Polish: 'Przeglądaj repozytoria i ich gałęzie w obszarze roboczym Azure DevOps lub GitHub.', Swedish: 'Bläddra i repositorier och deras grenar i ditt Azure DevOps- eller GitHub-arbetsområde.', Norwegian: 'Bla gjennom repoer og deres grener i Azure DevOps- eller GitHub-arbeidsområdet ditt.', Danish: 'Gennemse repositories og deres grene i dit Azure DevOps- eller GitHub-arbejdsområde.', Finnish: 'Selaa arkistoja ja niiden haaroja Azure DevOps- tai GitHub-työtilassasi.' },
  'pipeline.title': { English: 'Azure DevOps Pipelines', Spanish: 'Pipelines de Azure DevOps', French: 'Pipelines Azure DevOps', German: 'Azure DevOps-Pipelines', Italian: 'Pipeline Azure DevOps', Portuguese: 'Pipelines do Azure DevOps', Dutch: 'Azure DevOps-pijplijnen', Arabic: 'خطوط أنابيب Azure DevOps', Hindi: 'Azure DevOps पाइपलाइंस', Japanese: 'Azure DevOps パイプライン', Korean: 'Azure DevOps 파이프라인', 'Chinese (Simplified)': 'Azure DevOps 管道', 'Chinese (Traditional)': 'Azure DevOps 管道', Russian: 'Конвейеры Azure DevOps', Turkish: 'Azure DevOps Boru Hatları', Polish: 'Potoki Azure DevOps', Swedish: 'Azure DevOps-pipelines', Norwegian: 'Azure DevOps-pipelines', Danish: 'Azure DevOps-pipelines', Finnish: 'Azure DevOps-putket' },
  'pipeline.subtitle': { English: 'Track running, failed, and successfully completed pipelines for your current workstreams.', Spanish: 'Siga los pipelines en ejecución, fallidos y completados correctamente para sus flujos de trabajo actuales.', French: 'Suivez les pipelines en cours, en échec et terminés avec succès pour vos flux de travail actuels.', German: 'Verfolgen Sie laufende, fehlgeschlagene und erfolgreich abgeschlossene Pipelines für Ihre aktuellen Workstreams.', Italian: 'Segui pipeline in esecuzione, non riuscite e completate con successo per i tuoi flussi di lavoro attuali.', Portuguese: 'Acompanhe pipelines em execução, com falha e concluídos com sucesso para seus fluxos de trabalho atuais.', Dutch: 'Volg lopende, mislukte en succesvol voltooide pijplijnen voor uw huidige workstreams.', Arabic: 'تتبع خطوط الأنابيب الجارية والفاشلة والمكتملة بنجاح لتيارات العمل الحالية الخاصة بك.', Hindi: 'अपने वर्तमान वर्कस्ट्रीम के लिए चल रही, विफल और सफलतापूर्वक पूर्ण पाइपलाइंस पर नज़र रखें।', Japanese: '現在のワークストリームの実行中、失敗、正常完了したパイプラインを追跡します。', Korean: '현재 작업 흐름의 실행 중, 실패 및 성공적으로 완료된 파이프라인을 추적합니다.', 'Chinese (Simplified)': '跟踪当前工作流的运行中、失败和成功完成的管道。', 'Chinese (Traditional)': '追蹤當前工作流的執行中、失敗和成功完成的管道。', Russian: 'Отслеживайте выполняющиеся, провалившиеся и успешно завершенные конвейеры для ваших текущих рабочих процессов.', Turkish: 'Mevcut iş akışlarınız için çalışan, başarısız ve başarıyla tamamlanan boru hatlarını izleyin.', Polish: 'Śledź uruchomione, nieudane i pomyślnie zakończone potoki dla bieżących przepływów pracy.', Swedish: 'Spåra pågående, misslyckade och framgångsrikt slutförda pipelines för dina aktuella arbetsflöden.', Norwegian: 'Følg kjørende, mislykkede og vellykkede fullførte pipelines for dine nåværende arbeidsflyter.', Danish: 'Følg kørende, mislykkede og succesfuldt gennemførte pipelines for dine nuværende arbejdsgange.', Finnish: 'Seuraa nykyisten työvirtajesi käynnissä olevia, epäonnistuneita ja onnistuneesti suoritettuja putkia.' },
  'quality.title': { English: 'Code Quality', Spanish: 'Calidad del código', French: 'Qualité du code', German: 'Code-Qualität', Italian: 'Qualità del codice', Portuguese: 'Qualidade do código', Dutch: 'Codekwaliteit', Arabic: 'جودة الكود', Hindi: 'कोड गुणवत्ता', Japanese: 'コード品質', Korean: '코드 품질', 'Chinese (Simplified)': '代码质量', 'Chinese (Traditional)': '代碼品質', Russian: 'Качество кода', Turkish: 'Kod Kalitesi', Polish: 'Jakość kodu', Swedish: 'Kodkvalitet', Norwegian: 'Kodekvalitet', Danish: 'Kodekvalitet', Finnish: 'Koodin laatu' },
  'quality.subtitle': { English: 'A summary of automated code quality checks and published results for review.', Spanish: 'Un resumen de las comprobaciones automatizadas de calidad del código y los resultados publicados para revisión.', French: 'Un résumé des contrôles automatisés de la qualité du code et des résultats publiés pour examen.', German: 'Eine Zusammenfassung automatisierter Code-Qualitätsprüfungen und veröffentlichter Ergebnisse zur Überprüfung.', Italian: 'Un riepilogo dei controlli automatici di qualità del codice e dei risultati pubblicati per la revisione.', Portuguese: 'Um resumo das verificações automatizadas da qualidade do código e dos resultados publicados para revisão.', Dutch: 'Een samenvatting van geautomatiseerde codekwaliteitscontroles en gepubliceerde resultaten voor review.', Arabic: 'ملخص لفحوصات جودة الكود الآلية والنتائج المنشورة للمراجعة.', Hindi: 'समीक्षा के लिए स्वचालित कोड गुणवत्ता जाँच और प्रकाशित परिणामों का सारांश।', Japanese: 'レビュー用の自動コード品質チェックと公開結果の要約。', Korean: '검토를 위한 자동 코드 품질 검사 및 게시된 결과 요약입니다.', 'Chinese (Simplified)': '自动代码质量检查和已发布结果的摘要，供审核使用。', 'Chinese (Traditional)': '自動代碼品質檢查和已發佈結果的摘要，供審核使用。', Russian: 'Сводка автоматизированных проверок качества кода и опубликованных результатов для обзора.', Turkish: 'İnceleme için otomatik kod kalitesi kontrolleri ve yayımlanmış sonuçların özeti.', Polish: 'Podsumowanie automatycznych kontroli jakości kodu i opublikowanych wyników do weryfikacji.', Swedish: 'En sammanfattning av automatiska kodkvalitetskontroller och publicerade resultat för granskning.', Norwegian: 'En oppsummering av automatiserte kodekvalitetskontroller og publiserte resultater for gjennomgang.', Danish: 'Et resumé af automatiserede kodekvalitetskontroller og offentliggjorte resultater til gennemgang.', Finnish: 'Yhteenveto automatisoiduista koodin laatucheckeista ja julkaistuista tuloksista tarkastelua varten.' },
  'quality.passed': { English: 'Passed', Spanish: 'Aprobado', French: 'Réussi', German: 'Bestanden', Italian: 'Superato', Portuguese: 'Aprovado', Dutch: 'Geslaagd', Arabic: 'تم', Hindi: 'पास', Japanese: '合格', Korean: '통과', 'Chinese (Simplified)': '通过', 'Chinese (Traditional)': '通過', Russian: 'Пройдено', Turkish: 'Başarılı', Polish: 'Zaliczone', Swedish: 'Godkänd', Norwegian: 'Bestått', Danish: 'Bestået', Finnish: 'Läpäisty' },
  'quality.warning': { English: 'Warning', Spanish: 'Advertencia', French: 'Avertissement', German: 'Warnung', Italian: 'Avviso', Portuguese: 'Aviso', Dutch: 'Waarschuwing', Arabic: 'تحذير', Hindi: 'चेतावनी', Japanese: '警告', Korean: '경고', 'Chinese (Simplified)': '警告', 'Chinese (Traditional)': '警告', Russian: 'Предупреждение', Turkish: 'Uyarı', Polish: 'Ostrzeżenie', Swedish: 'Varning', Norwegian: 'Advarsel', Danish: 'Advarsel', Finnish: 'Varoitus' },
  'quality.failed': { English: 'Failed', Spanish: 'Fallido', French: 'Échec', German: 'Fehlgeschlagen', Italian: 'Non riuscito', Portuguese: 'Falhou', Dutch: 'Mislukt', Arabic: 'فشل', Hindi: 'विफल', Japanese: '失敗', Korean: '실패', 'Chinese (Simplified)': '失败', 'Chinese (Traditional)': '失敗', Russian: 'Не удалось', Turkish: 'Başarısız', Polish: 'Niepowodzenie', Swedish: 'Misslyckades', Norwegian: 'Mislyktes', Danish: 'Mislykkedes', Finnish: 'Epäonnistui' },
  'settings.title': { English: 'Settings', Spanish: 'Configuración', French: 'Paramètres', German: 'Einstellungen', Italian: 'Impostazioni', Portuguese: 'Configurações', Dutch: 'Instellingen', Arabic: 'الإعدادات', Hindi: 'सेटिंग्स', Japanese: '設定', Korean: '설정', 'Chinese (Simplified)': '设置', 'Chinese (Traditional)': '設定', Russian: 'Настройки', Turkish: 'Ayarlar', Polish: 'Ustawienia', Swedish: 'Inställningar', Norwegian: 'Innstillinger', Danish: 'Indstillinger', Finnish: 'Asetukset' },
  'settings.theme': { English: 'Theme', Spanish: 'Tema', French: 'Thème', German: 'Thema', Italian: 'Tema', Portuguese: 'Tema', Dutch: 'Thema', Arabic: 'السمة', Hindi: 'थीम', Japanese: 'テーマ', Korean: '테마', 'Chinese (Simplified)': '主题', 'Chinese (Traditional)': '主題', Russian: 'Тема', Turkish: 'Tema', Polish: 'Motyw', Swedish: 'Tema', Norwegian: 'Tema', Danish: 'Tema', Finnish: 'Teema' },
  'settings.themeDescription': { English: 'Choose how the dashboard should appear:', Spanish: 'Elija cómo debe aparecer el panel:', French: 'Choisissez l’apparence du tableau de bord :', German: 'Wählen Sie aus, wie das Dashboard erscheinen soll:', Italian: 'Scegli come deve apparire la dashboard:', Portuguese: 'Escolha como o painel deve aparecer:', Dutch: 'Kies hoe het dashboard moet verschijnen:', Arabic: 'اختر كيف يجب أن يظهر اللوحة:', Hindi: 'चुनें कि डैशबोर्ड कैसे दिखाई देना चाहिए:', Japanese: 'ダッシュボードの表示方法を選択してください:', Korean: '대시보드가 표시되는 방식을 선택하세요:', 'Chinese (Simplified)': '选择仪表板的显示方式：', 'Chinese (Traditional)': '選擇儀表板的顯示方式：', Russian: 'Выберите, как будет выглядеть панель:', Turkish: 'Kontrol panelinin nasıl görünmesini istediğinizi seçin:', Polish: 'Wybierz sposób wyświetlania pulpitu:', Swedish: 'Välj hur instrumentpanelen ska visas:', Norwegian: 'Velg hvordan kontrollpanelet skal vises:', Danish: 'Vælg, hvordan dashboardet skal vises:', Finnish: 'Valitse, miltä kojelauta näyttää:' },
  'settings.language': { English: 'Select your language', Spanish: 'Seleccione su idioma', French: 'Sélectionnez votre langue', German: 'Wählen Sie Ihre Sprache', Italian: 'Seleziona la tua lingua', Portuguese: 'Selecione seu idioma', Dutch: 'Selecteer uw taal', Arabic: 'اختر لغتك', Hindi: 'अपनी भाषा चुनें', Japanese: '言語を選択', Korean: '언어를 선택하세요', 'Chinese (Simplified)': '选择您的语言', 'Chinese (Traditional)': '選擇您的語言', Russian: 'Выберите язык', Turkish: 'Dil seçin', Polish: 'Wybierz swój język', Swedish: 'Välj ditt språk', Norwegian: 'Velg språket ditt', Danish: 'Vælg dit sprog', Finnish: 'Valitse kieli' },
  'settings.languageDescription': { English: 'Select your preferred display language for the portal.', Spanish: 'Seleccione su idioma de visualización preferido para el portal.', French: 'Sélectionnez votre langue d’affichage préférée pour le portail.', German: 'Wählen Sie Ihre bevorzugte Anzeigesprache für das Portal.', Italian: 'Seleziona la tua lingua di visualizzazione preferita per il portale.', Portuguese: 'Selecione seu idioma de exibição preferido para o portal.', Dutch: 'Selecteer uw voorkeurstaal voor het portaal.', Arabic: 'اختر لغة العرض المفضلة لك في البوابة.', Hindi: 'पोर्टल के लिए अपनी पसंदीदा डिस्प्ले भाषा चुनें।', Japanese: 'ポータルの表示言語を選択してください。', Korean: '포털의 표시 언어를 선택하세요.', 'Chinese (Simplified)': '为门户选择您偏好的显示语言。', 'Chinese (Traditional)': '為入口網站選擇您偏好的顯示語言。', Russian: 'Выберите предпочитаемый язык отображения для портала.', Turkish: 'Portal için tercih ettiğiniz görüntüleme dilini seçin.', Polish: 'Wybierz preferowany język wyświetlania portalu.', Swedish: 'Välj ditt föredragna visningsspråk för portalen.', Norwegian: 'Velg ønsket visningsspråk for portalen.', Danish: 'Vælg dit foretrukne visningssprog til portalen.', Finnish: 'Valitse portaalin ensisijainen näyttökieli.' },
  'settings.timezone': { English: 'Time zone', Spanish: 'Zona horaria', French: 'Fuseau horaire', German: 'Zeitzone', Italian: 'Fuso orario', Portuguese: 'Fuso horário', Dutch: 'Tijdzone', Arabic: 'المنطقة الزمنية', Hindi: 'समय क्षेत्र', Japanese: 'タイムゾーン', Korean: '시간대', 'Chinese (Simplified)': '时区', 'Chinese (Traditional)': '時區', Russian: 'Часовой пояс', Turkish: 'Zaman dilimi', Polish: 'Strefa czasowa', Swedish: 'Tidszon', Norwegian: 'Tidssone', Danish: 'Tidszone', Finnish: 'Aikavyöhyke' },
  'settings.timezoneDescription': { English: 'Set your local time zone for date/time display.', Spanish: 'Establezca su zona horaria local para la visualización de fecha y hora.', French: 'Définissez votre fuseau horaire local pour l’affichage date/heure.', German: 'Legen Sie Ihre lokale Zeitzone für die Anzeige von Datum/Uhrzeit fest.', Italian: 'Imposta il tuo fuso orario locale per la visualizzazione di data/ora.', Portuguese: 'Defina seu fuso horário local para a exibição de data/hora.', Dutch: 'Stel uw lokale tijdzone in voor datum-/tijdweergave.', Arabic: 'اضبط منطقتك الزمنية المحلية لعرض التاريخ والوقت.', Hindi: 'तिथि/समय प्रदर्शन के लिए अपना स्थानीय समय क्षेत्र सेट करें।', Japanese: '日付/時刻表示用にローカルタイムゾーンを設定します。', Korean: '날짜/시간 표시를 위한 로컬 시간대를 설정합니다.', 'Chinese (Simplified)': '设置您当地的时区以显示日期/时间。', 'Chinese (Traditional)': '設定您當地的時區以顯示日期/時間。', Russian: 'Установите ваш местный часовой пояс для отображения даты и времени.', Turkish: 'Tarih/saat gösterimi için yerel zaman diliminizi ayarlayın.', Polish: 'Ustaw swoją lokalną strefę czasową dla wyświetlania daty i czasu.', Swedish: 'Ställ in din lokala tidszon för datum-/tidsvisning.', Norwegian: 'Still inn din lokale tidssone for visning av dato og klokkeslett.', Danish: 'Indstil din lokale tidszone for dato-/klokkeslætsvisning.', Finnish: 'Aseta paikallinen aikavyöhykesi päivämäärän ja ajan näyttämistä varten.' },
  'common.brighterMode': { English: 'Brighter Mode', Spanish: 'Modo más brillante', French: 'Mode plus lumineux', German: 'Hellerer Modus', Italian: 'Modalità più luminosa', Portuguese: 'Modo mais claro', Dutch: 'Heldere modus', Arabic: 'وضع أكثر إشراقًا', Hindi: 'ब्राइटर मोड', Japanese: '明るいモード', Korean: '밝은 모드', 'Chinese (Simplified)': '更亮模式', 'Chinese (Traditional)': '更亮模式', Russian: 'Более яркий режим', Turkish: 'Daha Parlak Mod', Polish: 'Jaśniejszy tryb', Swedish: 'Ljuskare läge', Norwegian: 'Lysere modus', Danish: 'Lysere tilstand', Finnish: 'Kirkkaampi tila' },
  'common.lightMode': { English: 'Light Mode', Spanish: 'Modo claro', French: 'Mode clair', German: 'Heller Modus', Italian: 'Modalità chiara', Portuguese: 'Modo claro', Dutch: 'Lichte modus', Arabic: 'الوضع الفاتح', Hindi: 'लाइट मोड', Japanese: 'ライトモード', Korean: '라이트 모드', 'Chinese (Simplified)': '浅色模式', 'Chinese (Traditional)': '淺色模式', Russian: 'Светлый режим', Turkish: 'Açık Mod', Polish: 'Tryb jasny', Swedish: 'Ljust läge', Norwegian: 'Lyst modus', Danish: 'Lyst tilstand', Finnish: 'Vaalea tila' },
  'common.currentSelection': { English: 'Current selection:', Spanish: 'Selección actual:', French: 'Sélection actuelle :', German: 'Aktuelle Auswahl:', Italian: 'Selezione corrente:', Portuguese: 'Seleção atual:', Dutch: 'Huidige selectie:', Arabic: 'الاختيار الحالي:', Hindi: 'वर्तमान चयन:', Japanese: '現在の選択:', Korean: '현재 선택:', 'Chinese (Simplified)': '当前选择：', 'Chinese (Traditional)': '當前選擇：', Russian: 'Текущий выбор:', Turkish: 'Mevcut seçim:', Polish: 'Aktualny wybór:', Swedish: 'Nuvarande val:', Norwegian: 'Nåværende valg:', Danish: 'Nuværende valg:', Finnish: 'Nykyinen valinta:' },
  'common.localTimeZone': { English: 'Local time zone:', Spanish: 'Zona horaria local:', French: 'Fuseau horaire local :', German: 'Lokale Zeitzone:', Italian: 'Fuso orario locale:', Portuguese: 'Fuso horário local:', Dutch: 'Lokale tijdzone:', Arabic: 'المنطقة الزمنية المحلية:', Hindi: 'स्थानीय समय क्षेत्र:', Japanese: 'ローカルタイムゾーン:', Korean: '로컬 시간대:', 'Chinese (Simplified)': '本地时区：', 'Chinese (Traditional)': '本地時區：', Russian: 'Местный часовой пояс:', Turkish: 'Yerel zaman dilimi:', Polish: 'Lokalna strefa czasowa:', Swedish: 'Lokal tidszon:', Norwegian: 'Lokal tidssone:', Danish: 'Lokal tidszone:', Finnish: 'Paikallinen aikavyöhyke:' },
  'common.selectedLanguage': { English: 'Selected language:', Spanish: 'Idioma seleccionado:', French: 'Langue sélectionnée :', German: 'Ausgewählte Sprache:', Italian: 'Lingua selezionata:', Portuguese: 'Idioma selecionado:', Dutch: 'Geselecteerde taal:', Arabic: 'اللغة المختارة:', Hindi: 'चयनित भाषा:', Japanese: '選択された言語:', Korean: '선택한 언어:', 'Chinese (Simplified)': '所选语言：', 'Chinese (Traditional)': '所選語言：', Russian: 'Выбранный язык:', Turkish: 'Seçilen dil:', Polish: 'Wybrany język:', Swedish: 'Valt språk:', Norwegian: 'Valgt språk:', Danish: 'Valgt sprog:', Finnish: 'Valittu kieli:' }
};

export const languageOptions: LanguageOption[] = [
  'English', 'Spanish', 'French', 'German', 'Italian', 'Portuguese', 'Dutch', 'Arabic', 'Hindi', 'Japanese', 'Korean', 'Chinese (Simplified)', 'Chinese (Traditional)', 'Russian', 'Turkish', 'Polish', 'Swedish', 'Norwegian', 'Danish', 'Finnish'
];

interface LanguageContextValue {
  language: LanguageOption;
  setLanguage: (value: LanguageOption) => void;
  t: (key: string, fallback?: string) => string;
  languageOptions: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageOption>(() => {
    if (typeof window === 'undefined') return 'English';
    return (window.localStorage.getItem(LANGUAGE_KEY) as LanguageOption | null) || 'English';
  });

  const setLanguage = (value: LanguageOption) => {
    setLanguageState(value);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(LANGUAGE_KEY, value);
    }
  };

  const t = (key: string, fallback?: string) => {
    const translation = translations[key]?.[language] ?? fallback ?? translations[key]?.English ?? key;
    return translation;
  };

  const value = useMemo(() => ({ language, setLanguage, t, languageOptions }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
